apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wesley@trcx.com.br
    privateKeySecretRef:
      name: letsencrypt-tls
    solvers:
    - http01:
        ingress: 
          class: nginx

# VERSÂO CERT MANAGER CORRETA! kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.3/cert-manager.yaml
