apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector: 
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: "wtrcx/5_kubernetes_iniciando:v6.1"
          envFrom:
           - configMapRef:
              name: goserver-env
           - secretRef:
               name: goserver-secret
          volumeMounts:
            - mountPath: "/go/src/app/myfamily"
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: goserver-family-env
            items:
              - key: members
                path: "family.txt"
